properties:
  consul:
    require_ssl: false
    agent:
      servers:
        lan:
          - 127.0.0.1
  loggregator:
    etcd:
      machines:
        - etcd1.foo.bar
  metron_endpoint:
    shared_secret: secret123
  diego:
    rep:
      bbs:
        require_ssl: false

jobs:
  - properties:
      diego:
        rep:
          zone:
            zone1
